apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer
    image: nginx
    volumeMounts:
    - mountPath: /mnt
      name: nfs
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs
      readOnly: false